#!/bin/bash

# V5.34 vs V5.35 Backtest Comparison Script
# This script will guide you through running the comparison via the API

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║           V5.34 BASELINE vs V5.35 OPTIMIZED COMPARISON                     ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "V5.35 Optimizations:"
echo "  1. ✓ Trailing Stop: Widen threshold 2% → 3% (tighter control on medium winners)"
echo "  2. ✓ Momentum Reversal: 2-candle confirmation (reduces false exits)"
echo "  3. ✓ State Persistence: Database fields added for restart safety"
echo ""
echo "Goal: Maximize win rate, reduce losses WITHOUT impacting wins"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""

# Check if backend is running
if ! curl -s http://localhost:3000/api/auth/health > /dev/null 2>&1; then
    echo "❌ Backend is not running!"
    echo ""
    echo "Please start the backend first:"
    echo "  cd backend && npm run dev"
    echo ""
    exit 1
fi

echo "✅ Backend is running"
echo ""

# Get JWT token (you'll need to provide your credentials)
echo "To run backtests via API, you need authentication."
echo ""
echo "Option 1: Run backtest via frontend"
echo "  1. Start frontend: cd frontend && npm run dev"
echo "  2. Navigate to http://localhost:5173/backtest"
echo "  3. Configure:"
echo "     - Period: 2024-01-01 to 2024-12-31 (12 months)"
echo "     - Symbols: DOGE, IMX, SEI, SUI, XRP, ETH"
echo "     - Capital: \$10,000"
echo "     - Leverage: 5x"
echo "  4. Click 'Run Backtest'"
echo "  5. Save results to compare"
echo ""
echo "Option 2: Use curl with JWT token"
echo "  1. Login and get JWT token"
echo "  2. Run backtest API call (see instructions below)"
echo ""

echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📝 MANUAL COMPARISON STEPS:"
echo ""
echo "STEP 1: Temporarily revert to V5.34 (baseline)"
echo "  Edit backend/src/strategies/momentumSimple.ts:"
echo "    Line 242: TRAILING_WIDEN_AT_PCT: 2.0  (change from 3.0 to 2.0)"
echo ""
echo "  Edit backend/src/strategies/momentumSimple.ts line 1337-1363:"
echo "    Revert momentum reversal to single candle (remove 2-candle logic)"
echo ""
echo "STEP 2: Run V5.34 baseline backtest via frontend"
echo "  Save results as 'V5.34-baseline.json'"
echo ""
echo "STEP 3: Restore V5.35 optimizations"
echo "  Edit backend/src/strategies/momentumSimple.ts:"
echo "    Line 242: TRAILING_WIDEN_AT_PCT: 3.0  (restore)"
echo "    Lines 1337-1363: Restore 2-candle confirmation"
echo ""
echo "STEP 4: Run V5.35 optimized backtest via frontend"
echo "  Save results as 'V5.35-optimized.json'"
echo ""
echo "STEP 5: Compare Results"
echo "  Compare these key metrics:"
echo "    - Win Rate (goal: increase)"
echo "    - Losing Trades count (goal: reduce)"
echo "    - Avg Loss size (goal: reduce)"
echo "    - Total ROI (goal: maintain or improve)"
echo "    - Momentum Reversal exits (should be fewer with 2-candle)"
echo ""
echo "DECISION CRITERIA:"
echo "  ✅ IMPLEMENT V5.35 if:"
echo "     - Win rate improved OR same"
echo "     - Loss count reduced OR same"
echo "     - Avg loss smaller OR same"
echo "     - ROI improved OR within 5%"
echo ""
echo "  ❌ KEEP V5.34 if:"
echo "     - Win rate decreased significantly (> 2%)"
echo "     - ROI decreased significantly (> 10%)"
echo "     - No meaningful improvement in losses"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "Current status: V5.35 code is ALREADY implemented"
echo ""
echo "If you want to run the comparison, you have two options:"
echo "  A) Follow manual steps above"
echo "  B) Use the automated comparison (requires compiled TypeScript)"
echo ""
echo "For automated comparison:"
echo "  cd backend && npm run build && npm run compare:versions"
echo ""
