-- Generated by prisma migrate diff (create-only)
-- Adds supporting indexes for hot query paths and AI metrics columns

CREATE INDEX "AgentSession_stoppedAt_startedAt_idx" ON "AgentSession"("stoppedAt", "startedAt");
CREATE INDEX "Fill_sessionId_idx" ON "Fill"("sessionId");
CREATE INDEX "Fill_orderId_idx" ON "Fill"("orderId");
CREATE INDEX "Order_sessionId_createdAt_idx" ON "Order"("sessionId", "createdAt");
CREATE INDEX "Order_sessionId_status_idx" ON "Order"("sessionId", "status");
CREATE INDEX "Position_sessionId_idx" ON "Position"("sessionId");
CREATE INDEX "SentimentSnapshot_sessionId_idx" ON "SentimentSnapshot"("sessionId");
CREATE INDEX "Strategy_sessionId_idx" ON "Strategy"("sessionId");
CREATE INDEX "Strategy_symbol_createdAt_idx" ON "Strategy"("symbol", "createdAt");
CREATE INDEX "TriggerLog_sessionId_createdAt_idx" ON "TriggerLog"("sessionId", "createdAt");
CREATE INDEX "TriggerLog_createdAt_idx" ON "TriggerLog"("createdAt");

-- AI metrics columns on SessionKpi
ALTER TABLE "SessionKpi" ADD COLUMN     "aiByModel" JSONB,
ADD COLUMN     "aiCallsTotal" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "aiCostUsd" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "aiInputTokens" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "aiOutputTokens" INTEGER NOT NULL DEFAULT 0;
